version: '3.2'

services:
  bot:
    build:
      context: .
      args:
      - APP_VERSION=0.0.1-SNAPSHOT
    container_name: tvt_bot
    ports:
      - "8880:8080"
    depends_on:
      - db
    env_file: .env
  db:
    env_file: .env
    image: postgres:11.5
    container_name: tvtbot-data
    volumes:
      - tvtbot_postgres:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - tvtbot_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  #host:guest
volumes:
  tvtbot_postgres:
  tvtbot_postgres_data:
  tvtbot_kafka_data: